apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-update-producer-api-deployment  # Nome do Deployment
  annotations:
    autor: Rodrigo Mahlow 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: contact-update-producer-api
  template:
    metadata:
      labels:
        app: contact-update-producer-api
    spec:
      containers:
      - name: contact-update-producer-api
        image: maxcedro/contactsupdateprod:latest
        ports:
        - containerPort: 3030 
        resources:
          limits:
            cpu: "0.5"
            memory: 512Mi
          requests:
            cpu: "0.2"
            memory: 256Mi
        env:
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: contact-update-producer-api-secrets
              key: DefaultConnection
        - name: SecretJWT
          valueFrom:
            secretKeyRef:
              name: contact-update-producer-api-secrets
              key: SecretJWT
        - name: MassTransit__User
          valueFrom:
            secretKeyRef:
              name: contact-update-producer-api-secrets
              key: User
        - name: MassTransit__Password
          valueFrom:
            secretKeyRef:
              name: contact-update-producer-api-secrets
              key: Password
        - name: MassTransit__QueueName"
          valueFrom:
            configMapKeyRef: 
              name: "contact-update-producer-api-configmap"
              key: "QueueName"        
        - name: MassTransit__Server
          valueFrom:
            configMapKeyRef: 
              name: "contact-update-producer-api-configmap"
              key: "Server"
        - name: "Integrations__ContactConsult__BasePath"
          valueFrom:
            configMapKeyRef: 
              name: "contact-update-producer-api-configmap"
              key: "BasePath"
        
       
